<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>c</string>
		<string>h</string>
	</array>
	<key>name</key>
	<string>KPL Kernel Programming Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Function, method declarations are highlighted</string>
			<key>match</key>
			<string>(?&lt;=function|method|class|behavior)\s*(\w+)</string>
			<key>name</key>
			<string>entity.name.function.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Ensures that user defined data types are highlighted</string>
			<key>match</key>
			<string>(?&lt;=new|of|ptr to|asPtrTo)\s+(\w+)</string>
			<key>name</key>
			<string>storage.type.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constants</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Native data types</string>
			<key>match</key>
			<string>\b(array|bool|char|double|float|int|long|signed|void)\b</string>
			<key>name</key>
			<string>storage.type.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>All the keywords in the language</string>
			<key>match</key>
			<string>\b(alloc|anyType|array|arraySize|asInteger|asPtrTo|behavior|bool|break|by|case|catch|char|class|code|const|continue|debug|default|do|else|elseIf|endBehavior|endClass|endCode|endFor|endFunction|endHeader|endIf|endInterface|endMethod|endRecord|endSwitch|endTry|endWhile|enum|errors|extends|external|false|fields|for|free|function|header|if|implements|infix|int|interface|isInstanceOf|isKindOf|messages|method|methods|new|null|of|prefix|ptr|record|renaming|return|returns|self|sizeOf|suer|superclass|switch|throw|to|true|try|type|typeOfNull|until|uses|var|void|while)\b</string>
			<key>name</key>
			<string>keyword.source.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single line comments</string>
			<key>match</key>
			<string>--.*$</string>
			<key>name</key>
			<string>comment.kpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>Multi-line comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.kpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.kpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.hex.kpl</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.linefeed.kpl</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.return.kpl</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.tab.kpl</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.vertical-tab.kpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.octal.kpl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.newline.kpl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.backlash.kpl</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.double-quote.kpl</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.single-quote.kpl</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.bell.kpl</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.backspace.kpl</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.formfeed.kpl</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Highlights escaped characters within strings</string>
					<key>match</key>
					<string>(\\x[0-9A-F]{2})|(\\[0-7]{3})|(\\\n)|(\\\\)|(\\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\n)|(\\r)|(\\t)|(\\v)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Various number. I grabbed this from the python files so I don't know if it'll cause any weird issues, but it seems to work so far</string>
			<key>match</key>
			<string>\b(?i:(0x\h*))</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0[0-7]+)</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(((\d+(\.(?=[^a-zA-Z_])\d*)?|(?&lt;=[^0-9a-zA-Z_])\.\d+)(e[\-\+]?\d+)?))J)</string>
			<key>name</key>
			<string>constant.numeric.complex.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^a-zA-Z_])</string>
			<key>name</key>
			<string>constant.numeric.float.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[^0-9a-zA-Z_])(?i:(\.\d+(e[\-\+]?\d+)?))</string>
			<key>name</key>
			<string>constant.numeric.float.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+e[\-\+]?\d+))</string>
			<key>name</key>
			<string>constant.numeric.float.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|\/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.kpl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kpl</string>
	<key>uuid</key>
	<string>16e882cc-c040-4150-a096-c175197698ff</string>
</dict>
</plist>
