<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>c</string>
		<string>h</string>
	</array>
	<key>name</key>
	<string>KPL Kernel Programming Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(function|method)\s+([A-Za-z_][A-Za-z0-9_]*\s*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.kpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kpl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matches function names</string>
			<key>end</key>
			<string>(\()</string>
			<key>name</key>
			<string>meta.function.kpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(class|behavior)\s+([A-Za-z_][A-Za-z0-9_]*\s*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.kpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kpl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matches function names</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.function.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Ensures that user defined data types are highlighted</string>
			<key>match</key>
			<string>(?&lt;=new|of|ptr to|asPtrTo)\s+(?!new)(\w+)</string>
			<key>name</key>
			<string>storage.type.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constants</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Native data types</string>
			<key>match</key>
			<string>\b(array|bool|char|double|float|int|long|signed|void)\b</string>
			<key>name</key>
			<string>storage.type.kpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(superclass)\s+([A-Za-z_][A-Za-z0-9_]*\s*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.kpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.kpl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matches function names</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.function.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>All the keywords in the language</string>
			<key>match</key>
			<string>\b(alloc|anyType|array|arraySize|asInteger|asPtrTo|behavior|bool|break|by|case|catch|char|class|code|const|continue|debug|default|do|else|elseIf|endBehavior|endClass|endCode|endFor|endFunction|endHeader|endIf|endInterface|endMethod|endRecord|endSwitch|endTry|endWhile|enum|errors|extends|external|false|fields|for|free|function|header|if|implements|infix|int|interface|isInstanceOf|isKindOf|messages|method|methods|new|null|of|prefix|ptr|record|renaming|return|returns|self|sizeOf|suer|superclass|switch|throw|to|true|try|type|typeOfNull|until|uses|var|void|while)\b</string>
			<key>name</key>
			<string>keyword.source.kpl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single line comments</string>
			<key>match</key>
			<string>--.*$</string>
			<key>name</key>
			<string>comment.kpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>Multi-line comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.kpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Double quoted strings</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.kpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>Single quoted strings</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.kpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Various number. I grabbed this from the kpl files so I don't know if it'll cause any weird issues, but it seems to work so far</string>
			<key>match</key>
			<string>\b(?i:(0x\h*))</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0[0-7]+)</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(((\d+(\.(?=[^a-zA-Z_])\d*)?|(?&lt;=[^0-9a-zA-Z_])\.\d+)(e[\-\+]?\d+)?))J)</string>
			<key>name</key>
			<string>constant.numeric.complex.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^a-zA-Z_])</string>
			<key>name</key>
			<string>constant.numeric.float.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[^0-9a-zA-Z_])(?i:(\.\d+(e[\-\+]?\d+)?))</string>
			<key>name</key>
			<string>constant.numeric.float.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+e[\-\+]?\d+))</string>
			<key>name</key>
			<string>constant.numeric.float.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|\/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.kpl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.kpl</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>entity_name_function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generic_names</string>
				</dict>
			</array>
		</dict>
		<key>generic_names</key>
		<dict>
			<key>match</key>
			<string>[A-Za-z_][A-Za-z0-9_]*</string>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abefnprtv'"?]|[0-3]\d{,2}|[4-7]\d?|x[a-fA-F0-9]{,2}|u[a-fA-F0-9]{,4}|U[a-fA-F0-9]{,8})</string>
					<key>name</key>
					<string>constant.character.escape.kpl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.kpl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.kpl</string>
	<key>uuid</key>
	<string>16e882cc-c040-4150-a096-c175197698ff</string>
</dict>
</plist>
